version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8081:8080"  # Mapeia a porta 8080 do host para a porta 80 do contêiner
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge